package com.tensorspace.paperai

import android.content.Context
import io.objectbox.BoxStore

/**
 * ObjectBox singleton - provides global access to our vector database.
 *
 * In Android, we need to be careful about how we initialize things that require
 * a Context (like databases, file access, etc.). We can't just create them at
 * the top of a file because Context isn't available until the app starts.
 *
 * This singleton pattern solves that:
 * 1. The app's Application class calls init() when the app starts
 * 2. After that, any code can access the database via ObjectBox.store
 *
 * BoxStore is ObjectBox's main database class. It manages all the "boxes"
 * (think of boxes as tables - one box per entity type). We have one box
 * for DocumentChunk objects.
 */
object ObjectBox {

    /**
     * The BoxStore instance. This is lateinit because we can't create it until
     * we have a Context, which only happens when the app starts.
     *
     * lateinit is Kotlin's way of saying "I promise this will be initialized
     * before anyone tries to use it." If you access it before init() is called,
     * you'll get a crash - that's intentional, as it indicates a bug.
     */
    lateinit var store: BoxStore
        private set  // Only this object can set the store; others can only read it

    /**
     * Initialize the database. Must be called once when the app starts,
     * before any database operations are attempted.
     *
     * @param context The application context. We use applicationContext to avoid
     *                memory leaks (activity contexts can be leaked if held too long).
     */
    fun init(context: Context) {
        // MyObjectBox is auto-generated by the ObjectBox plugin based on our
        // @Entity classes. It knows about DocumentChunk and creates the
        // appropriate database schema.
        //
        // The database files are stored in the app's private directory,
        // typically at: /data/data/com.tensorspace.paperai/files/objectbox/
        store = MyObjectBox.builder()
            .androidContext(context.applicationContext)
            .build()
    }

    /**
     * Convenience property to get the DocumentChunk box directly.
     *
     * A "box" in ObjectBox is like a table in SQL - it holds all objects of
     * a specific type. This property lets us write:
     *     ObjectBox.chunkBox.put(myChunk)
     * instead of:
     *     ObjectBox.store.boxFor(DocumentChunk::class.java).put(myChunk)
     */
    val chunkBox
        get() = store.boxFor(DocumentChunk::class.java)
}